[Feat] 경기 상세 정보 + location, stadium 정보 조회 메소드 구현
4JOCHAMCHI/YAGUROUTE pull request #65
Opened 2024-07-26 09:48 UTC by jaehyeon-SMU

### 변경 사항
 경기 상세 정보 + location, stadium 정보 조회 메소드 구현

### 이슈 번호
#64 

### 테스트 결과
모두 정상적으로 동작

2024-07-26 16:35 UTC, goeunpark123 requested changes
긴 쿼리 작성하시느라 수고하셨습니다~ 잘 쓰겠습니다!

2024-07-26 16:35 UTC, goeunpark123 commented on yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameController.java
detail 오타나신 것 같아요!

2024-07-26 16:35 UTC, goeunpark123 commented on yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameController.java
정말 조심스럽게 아마 이 메소드 서비스에서만 사용할 것 같다고 말씀 드리고 싶습니다..
프론트에서 쓰일 일이 있다면 억지로라도 써보겠습니다.

2024-07-30 03:39 UTC, jaehyeon-SMU commented on yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameController.java
감사합니다. 수정하겠습니다!

2024-07-30 03:40 UTC, jaehyeon-SMU commented on yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameController.java
억지로 안쓰셔도 됩니다 ㅎㅎ

2024-07-30 03:57 UTC, goeunpark123 approved these changes

2024-07-30 03:58 UTC, hky0715 approved these changes
최고입니다 🥹

2024-07-30 04:04 UTC, merged